github:
- .github/**/*

taxonomies:
- .github/**/*
- androidTest/java/openfoodfacts/github/scrachx/openfood/repositories/TaxonomiesRepositoryTest.kt
- main/java/openfoodfacts/github/scrachx/openfood/repositories/TaxonomiesManager.kt
- main/java/openfoodfacts/github/scrachx/openfood/repositories/Taxonomy.kt
- main/java/openfoodfacts/github/scrachx/openfood/repositories/TaxonomiesRepository.kt

allergen alert:
.//test/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenResponseTestData.kt
.//test/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergensWrapperTest.kt
.//test/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenTest.kt
.//test/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenResponseTest.kt
.//main/java/openfoodfacts/github/scrachx/openfood/features/allergensalert/AllergensAlertViewModel.kt
.//main/java/openfoodfacts/github/scrachx/openfood/features/allergensalert/AllergensAdapter.kt
.//main/java/openfoodfacts/github/scrachx/openfood/features/allergensalert/AllergensAlertFragment.kt
.//main/java/openfoodfacts/github/scrachx/openfood/repositories/AllergenPreferencesRepository.kt
.//main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenResponse.kt
.//main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenName.java
.//main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergensWrapperDeserializer.kt
.//main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergensWrapper.kt
.//main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/Allergen.java
.//main/java/openfoodfacts/github/scrachx/openfood/models/entities/allergen/AllergenHelper.kt

screenshots:
.//androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/test/ScreenshotParameter.kt
.//androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/test/ScreenshotActivityTestRule.kt
.//androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/test/ScreenshotTaker.kt
.//androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/test/ScreenshotParametersProvider.kt
.//androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/test/ScreenshotsLocaleProvider.kt

translations:
./off/res/values-*
./obf/res/values-*
./opf/res/values-*
./opff/res/values-*

open beauty facts:
./obf/res/values-*

open products facts:
./opf/res/values-*

open pet food facts:
./opff/res/values-*

changelog:
./main/assets/changelog/*
